global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mechanicshop-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:80']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
